### ISSUE TITLE
Web->VC: Issues listes below

### ISSUE THREAD

**Issue by nirajkumarvinove** [Vinove-Properties/valuecoders.com#20]
1.Spacing issue : https://prnt.sc/aVXe0zq58ePH
2. This section is not exist in figma : https://prnt.sc/IT8mOVjBcYGX
3. Arrow touching with text: https://prnt.sc/4CLn3CdYZHxd 
4. Not matching with each other: https://prnt.sc/D9DGJyZT99W3
5. Numbering not matching+Alignments issues
SS: https://prnt.sc/SFyzvrjvd1mo
URL: https://www.valuecoders.com/staging/ai
6. Responsive issue in 1920_900,  2560_1440,  1280_600 all pages

**Comment by nandanisinhavc** [comment]
1.Spacing issue : https://prnt.sc/aVXe0zq58ePH - Done

**Comment by nandanisinhavc** [comment]
1.Spacing issue : https://prnt.sc/aVXe0zq58ePH - Done, Please check with clear cache.
3. Arrow touching with text: https://prnt.sc/4CLn3CdYZHxd - Done
