### ISSUE TITLE
Web->VC: Responsive Issues + w3c validation errors

### ISSUE THREAD

**Issue by nirajkumarvinove** [Vinove-Properties/valuecoders.com#26]
URL: https://www.valuecoders.com/staging/hire-developers/hire-assembly-developers
Issue 1: Responsive issue in some system
SS: https://prnt.sc/zDhs26VvJxwz

Issue 2: Not responsive in mobile devices
SS: https://prnt.sc/y_GcPfkDZvCJ

Issue3: W3c validation errors

**Comment by nandanisinhavc** [comment]
Please check now

**Comment by nirajkumarvinove** [comment]
Done
