### ISSUE TITLE
Web->VC: Isue listed below

### ISSUE THREAD

**Issue by nirajkumarvinove** [Vinove-Properties/valuecoders.com#37]
Issue: External links should be open in anotrher tab
URL: https://www.valuecoders.com/staging/healthcare/chatbot-development
SS: 
![image](https://github.com/user-attachments/assets/41841f28-77e1-4f05-ab63-f2dafd542c69)

Issue 2: Font should be matched 
URL: https://www.valuecoders.com/staging/healthcare/remote-patient-monitoring
SS: 
![image](https://github.com/user-attachments/assets/373d911f-feca-409f-9b18-e224a6c17011)

Issue 3: "Solution" with bold font should be in the beginning
URL: https://www.valuecoders.com/staging/healthcare/chatbot-development
SS: 
![image](https://github.com/user-attachments/assets/0ef67d37-deb4-4765-954c-da1c325d5a97)

**Comment by nandanisinhavc** [comment]
Please check now as we have fixed all the issues.

**Comment by nirajkumarvinove** [comment]
Done
