### ISSUE TITLE
Web->Web->About us: Remove Image 

### ISSUE THREAD

**Issue by nirajkumarvinove** [Vinove-Properties/valuecoders.com#5]
Issue 1: Remove Image
Url: https://www.valuecoders.com/about
SS: https://prnt.sc/qIwQsQmPtWfp

Issue 2: On vinove footer remove Mohali address

**Comment by nitinbalunivinove** [comment]
@nirajkumarvinove I have fixed this issue.

**Comment by nirajkumarvinove** [comment]
Done!
